export enum CheckInState {
  BEGIN_CONVERSATION = 'beginConversation',
  TRIP_IDENTIFICATION = 'tripIdentification',
  TRIP_SELECTION = 'tripSelection',
  JOURNEY_IDENTIFICATION = 'journeyIdentification',
  JOURNEY_SELECTION = 'journeySelection',
  PASSENGER_IDENTIFICATION = 'passengerIdentification',
  PASSENGER_SELECTION = 'passengerSelection',
  PASSENGER_INFORMATION = 'passengerInformation',
  DANGEROUS_GOODS = 'dangerousGoods',
  REGULATORY_DETAILS = 'regulatoryDetails',
  VALIDATE_PROCESS_CHECKIN = 'validateProcessCheckin',
  PROCESS_CHECK_IN = 'processCheckIn',
  CHECKIN_ACCEPTANCE = 'checkinAcceptance',
  SEAT_SELECTION = 'seatSelection',
  ANCILLARY_SELECTION = 'ancillarySelection',
  PAYMENT_PENDING = 'paymentPending',
  BOARDING_PASS = 'boardingPass',
  CONFIRMATION = 'confirmation',
}
